module.exports = {
    CONNECTION: 'connection',
    DISCONNECT: 'disconnect',
    INVITE_FRIEND: 'INVITE_FRIEND',
    QUIZ_JOIN: 'quiz-join',
    QUIZ_ROOM: 'quiz-room',
    QUIZ_START_LOADING_PLAYERS: 'quiz-start-loading-players',
    QUIZ_UPDATE_PLAYERS: 'quiz-update-players',
    QUIZ_LEAVE: 'quiz-leave',
    QUIZ_QUEUE_USER: 'quiz-queue-user',
    QUIZ_JOIN_SUCCESS: 'quiz-join-success',
    QUIZ_JOIN_ERROR: 'quiz-join-error',
    QUIZ_NEW_PLAYER: 'quiz-new-user',
    QUIZ_END_LOADING_PLAYERS: 'quiz-end-loading-players',
    QUIZ_START_COUNTDOWN: 'quiz-start-countdown',
    QUIZ_WAIT_ANIMATION: 'quiz-wait-animation',
    QUIZ_MAKE_QUESTIONS: 'quiz-make-question',
    QUIZ_RETURN_QUESTIONS: 'quiz-return-questions',
    QUIZ_RANK: 'quiz-rank',

    QUIZ_START_QUESTION: 'quiz-question',
    QUIZ_ANSWER: 'quiz-answer',
    QUIZ_AUTO_ANSWER: 'quiz-auto-answer',
    QUIZ_ANSWER_RESPONSE: 'quiz-answer-response',
    QUIZ_PREPARE_QUESTION: 'quiz-prepare-question',
    QUIZ_CLOSED: 'quiz-closed',
    QUIZ_LINK_MUSICS: 'quiz-link-musics',
    QUIZ_DELAY_LINK_MUSICS: 'quiz-delay-link-music',
    QUIZ_LINK_SUDDEN_DEATH: 'quiz-link-sudden-death',

}